### ISSUE TITLE
pipe branch connection bug

### ISSUE THREAD

**Issue by JohanDjarvKarltorp** [vattenbagarna/Frontend#34]
- Fix bug when user tries to add pipe branch connection to a pipe that have been edited and have multiple points.

When user does this today the pipe branch only connects to the first and last point on the pipe even if pipe have multiple points and the user wanted only two points in the middle.

- To fix this bug the system needs to find the two closest points from where the user clicked on the pipe and create pipe branch connection between them.

**Comment by SpaceLenore** [comment]
Closed in #38
